### ISSUE TITLE
Scrobbling not working

### ISSUE THREAD

**Issue by bradykimball** [asavartsov/cloudplayer-scrobbler#10]
I'm running Google Chrome on Mac (13.0.782.220).  I've reloaded Chrome, uninstalled the extension, reinstalled, logged out and back in, and I still cannot scrobble from my Amazon Cloud Player.

Any suggestions?

**Comment by case** [comment]
I'm using Beta Channel 14.0.835.186 and it isn't working for me either, unfortunately.

**Comment by asavartsov** [comment]
Sorry guys, I have no time to keep Amazon version updated now, so I pulled it out of webstore
