### ISSUE TITLE
Timestamps incorrect

### ISSUE THREAD

**Issue by jonahwh** [asavartsov/cloudplayer-scrobbler#6]
It seems that the timestamps the songs are scrobbled with are incorrect. Not only do they occur up to 7 hours in the past, but out of order. See this screenshot of songs I've listened to in the past 30 minutes with Google Music:
http://img135.imageshack.us/img135/4825/baeacbd8231849588da572e.png

This is an issue with the Google Music scrobbler

**Comment by asavartsov** [comment]
Shoud be fixed now. I'll keep the issue open for a while

**Comment by jonahwh** [comment]
Just confirming it's fixed.
